### ISSUE TITLE
Check the distance between your bg image and right block

### ISSUE THREAD

**Issue by heywhahappnd** [YevhenTkachuk/sports-app-landing#16]
http://joxi.ru/a2XLJk8HwMlze2
У тебя текст налазит на фон, на макете между ними немного есть расстояния

**Comment by YevhenTkachuk** [comment]
![image](https://user-images.githubusercontent.com/45273629/56733255-4990d900-6768-11e9-8176-b1e543e90550.png)

**Comment by YevhenTkachuk** [comment]
я думаю у меня такая же проблема
