### ISSUE TITLE
Cleanup readme and info in title

### ISSUE THREAD

**Issue by rudnitskih** [YevhenTkachuk/sports-app-landing#19]
![image](https://user-images.githubusercontent.com/8848858/56794982-1a39a500-6818-11e9-95f2-d8b9c6cc4702.png)

![image](https://user-images.githubusercontent.com/8848858/56794998-2291e000-6818-11e9-8b98-ba46b7cdc3a5.png)

**Comment by rudnitskih** [comment]
Remove asterisks - 
![image](https://user-images.githubusercontent.com/8848858/56815668-9947d100-684a-11e9-92bd-08d482fb504e.png)

**Comment by YevhenTkachuk** [comment]
Исправил)
