### ISSUE TITLE
Когда создашь пользователя с норм именем?

### ISSUE THREAD

**Issue by rudnitskih** [YevhenTkachuk/sports-app-landing#20]
![image](https://user-images.githubusercontent.com/8848858/56795031-3b01fa80-6818-11e9-9bf6-c7f20634ac3e.png)

**Comment by YevhenTkachuk** [comment]
просто не знаю как изменить ето имя без потери проектов )

**Comment by rudnitskih** [comment]
никакак - их нужно будет перенести правильно

поэтому я и говорил сделать это максимально раньше

**Comment by rudnitskih** [comment]
Хотя нет вру - https://stackoverflow.com/questions/9191918/change-github-account-username
